version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday
    commit-message:
      prefix: "chore(deps)"
    groups:
      go-minor-patch:
        update-types: [ "minor","patch" ]
        patterns:
          - "*"
      go-major:
        update-types: [ "major" ]
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday
    commit-message:
      prefix: "chore(deps)"
    groups:
      github-actions-minor-patch:
        update-types: [ "minor", "patch" ]
        patterns:
          - "*"
      github-actions-major:
        update-types: [ "major" ]
        patterns:
          - "*"
