version: 2
updates:
  # Create grouped PRs for all minor and patch updates to Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday
    commit-message:
      prefix: "chore(deps)"
    groups:
      go:
        update-types: [ "patch", "minor" ]

    # Create grouped PRs for all minor and patch updates to GitHub actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday
    commit-message:
      prefix: "chore(deps)"
    groups:
      github-actions:
        update-types: [ "patch", "minor" ]
