name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        go-version: ["1.15"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: golangci-lint
        continue-on-error: true
        uses: golangci/golangci-lint-action@v6
        with:
          args: --issues-exit-code=0 --timeout=5m

      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...

      - name: Upload to codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true

  changie:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare release
        uses: labd/changie-release-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-workflow: 'release.yaml'
