name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        go-version: ["1.15"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...

      - name: Upload to codecov
        uses: codecov/codecov-action@v4.3.1
